Rename test.js to test.ts
probot/template-typescript pull request #1
Opened 2018-07-03 21:18 UTC by hiimbex

2018-07-05 04:13 UTC, tcbyrd requested changes
Thanks for this! I forgot to change the test.

Want to change the comments, too?
```
// You can import your modules
// const index = require('../index')
```

Would change to:
```
// You can import your modules
// import index from './index'
```

And maybe add or change the link at the bottom to [ts-jest](https://github.com/kulshekhar/ts-jest)? This is what Jest links to in their section on ["Using typescript"](https://jestjs.io/docs/en/getting-started#using-typescript)

2018-07-05 05:27 UTC, hiimbex commented
Good call @tcbyrd!

Just updated, let me know if you think the wording in the bottom section can be improved!

2018-07-05 14:19 UTC, tcbyrd commented on test/index.test.ts
> +// For using TypeScript in your tests, Jest recommends:
How about a mix of the old and the new?

> For more information about using TypeScript in your tests, Jest recommends:

2018-07-05 19:16 UTC, tcbyrd approved these changes

2018-07-13 05:45 UTC, JamesMGreene commented
FWIW, I integrated these changes into PR #2.

2018-07-13 05:55 UTC, JamesMGreene commented on test/index.test.ts
> +// import index from './index'
FWIW, although this is just a comment, the proposed path is not accurate. Should be `'../lib/index'`. I updated this in PR #2.

2018-07-16 17:26 UTC, JamesMGreene commented on test/index.test.ts
> +// import index from './index'
I talked with some local TypeScript users to get their thoughts on this.  They unanimously said that they import from `"src"` for tests because, conceptually, the goal of the test is to test the source logic rather than the transpiler.  I liked that way of thinking, so I've updated the comment in my PR (#2) to point to the `"src"` directory instead of `"lib"`. :+1:

2018-08-10 11:34 UTC, closed without merging